builds:
- main: ./cmd/kubectl-reap/main.go
  ldflags: 
    - -s -w
    - -X github.com/micnncim/kubectl-reap/pkg/version.Version={{.Tag}}
    - -X github.com/micnncim/kubectl-reap/pkg/version.Revision={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - "386"
  - amd64
  - arm64
  goarm:
  - "7"
  ignore:
  - goos: windows
    goarch: arm64
brews:
  - tap:
      owner: micnncim
      name: kubectl-reap
    folder: Formula
    homepage: https://github.com/micnncim/kubectl-reap
    description: kubectl plugin that deletes unused Kubernetes resources
