# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlReap < Formula
  desc "kubectl plugin that deletes unused Kubernetes resources"
  homepage "https://github.com/micnncim/kubectl-reap"
  version "0.11.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.3/kubectl-reap_0.11.3_darwin_amd64.tar.gz"
    sha256 "53c2074e2dcab8c4d513013de9bd9746f4c4504c4bf07fb4956607de4766ed20"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.3/kubectl-reap_0.11.3_linux_amd64.tar.gz"
    sha256 "ceec75c07a030717f2658a77c459767b653c31b9f204d767633535f28af57295"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.3/kubectl-reap_0.11.3_linux_arm64.tar.gz"
    sha256 "4af1337b93f2098eb5138349a6692b5a616470a7d2372890cd99cb3c30f7f532"
  end

  def install
    bin.install "kubectl-reap"
  end
end
