# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlReap < Formula
  desc "kubectl plugin that deletes unused Kubernetes resources"
  homepage "https://github.com/micnncim/kubectl-reap"
  version "0.11.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.2/kubectl-reap_0.11.2_darwin_amd64.tar.gz"
    sha256 "4d129c76cf6d5d07b561c1e4465ae2cdcec6ee2683ad19efedf201489ad552cf"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.2/kubectl-reap_0.11.2_linux_amd64.tar.gz"
    sha256 "a37e90cfa36dd377cd24e7ed49ca002286ffb4ca8bc5227af42516074201abde"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.2/kubectl-reap_0.11.2_linux_arm64.tar.gz"
    sha256 "390d31b63712348d0f268aa4fc5ba5354768d207c8a792e4587a93b076791249"
  end

  def install
    bin.install "kubectl-reap"
  end
end
