# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlReap < Formula
  desc "kubectl plugin that deletes unused Kubernetes resources"
  homepage "https://github.com/micnncim/kubectl-reap"
  version "0.11.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.1/kubectl-reap_0.11.1_darwin_amd64.tar.gz"
    sha256 "7192952833e9d4ac5a0df14434e13d8ac3eddbf4e2f166175160188aa0b96b69"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.1/kubectl-reap_0.11.1_linux_amd64.tar.gz"
    sha256 "fa1b7dd8230b938be4ec2ac905a26920eb944c649cd48bd0932a8939bd817267"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/micnncim/kubectl-reap/releases/download/v0.11.1/kubectl-reap_0.11.1_linux_arm64.tar.gz"
    sha256 "dad374185efe040ab1011f3e6f68ab3f3a2aa222c25ca1c122372dcc22666ede"
  end

  def install
    bin.install "kubectl-reap"
  end
end
